version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "empiricaapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6h0vxkxajwe5"
s3_prefix = "empiricaapi"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
